In [ ]:
import numpy

In [1]:
import pandas

In [2]:
import pandas as pd 
df=pd.read_csv("/home/user/Downloads/portland_housing.csv(1)/portland_housing.csv")
d=pd.DataFrame(df)

/tmp/ipykernel_3797/2166219974.py:2: DtypeWarning: Columns (20,50,161,200) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/home/user/Downloads/portland_housing.csv(1)/portland_housing.csv")

In [3]:
df.head()

,abbreviatedAddress,address/city,address/zipcode,bathrooms,bedrooms,brokerageName,dateSold,daysOnZillow,description,favoriteCount,...,taxHistory/0/taxPaid,taxHistory/0/time,taxHistory/0/value,taxHistory/0/valueIncreaseRate,url,yearBuilt,zestimate,zestimateHighPercent,zestimateLowPercent,zpid
0,2860 NE Blossom Hill Rd,Fairview,97024,3.0,3.0,NaN,1.621560e+12,25.0,"2860 NE Blossom Hill Rd, Fairview, OR 97024 is...",NaN,...,2989.74,1.592260e+12,172290.0,0.029950,https://www.zillow.com/homedetails/2860-NE-Blo...,2007.0,317406.0,5.0,5.0,72258538
1,20386 NE Mackenzie Ln,Fairview,97024,3.0,3.0,Harcourts Real Estate Network Group,1.619140e+12,53.0,Cute as a button 3bed/2.5bath home with brand ...,NaN,...,NaN,NaN,NaN,NaN,https://www.zillow.com/homedetails/20386-NE-Ma...,2001.0,NaN,NaN,NaN,2073593774
2,1121 SW 10th Dr,Gresham,97080,3.0,4.0,ERA Freeman & Associates,1.622760e+12,11.0,What a wonderful large home at end of quiet cu...,NaN,...,5178.62,1.592260e+12,282340.0,0.029987,https://www.zillow.com/homedetails/1121-SW-10t...,1982.0,512355.0,5.0,5.0,53959026
3,19309 NE Glisan St,Portland,97230,1.0,3.0,"Premiere Property Group, LLC",1.622760e+12,11.0,NaN,1.0,...,2420.36,1.497560e+12,142330.0,0.029959,https://www.zillow.com/homedetails/19309-NE-Gl...,1953.0,NaN,NaN,NaN,176563865
4,25-65 NW 20th St,Gresham,97030,3.0,6.0,NaN,1.622510e+12,14.0,"25-65 NW 20th St, Gresham, OR 97030 is a apart...",NaN,...,2809.61,1.592260e+12,153180.0,0.029989,https://www.zillow.com/homedetails/25-65-NW-20...,1967.0,NaN,NaN,NaN,53819568

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25731 entries, 0 to 25730
Columns: 348 entries, abbreviatedAddress to zpid
dtypes: bool(11), float64(111), int64(6), object(220)
memory usage: 66.4+ MB

In [5]:
df.columns

Index(['abbreviatedAddress', 'address/city', 'address/zipcode', 'bathrooms',
       'bedrooms', 'brokerageName', 'dateSold', 'daysOnZillow', 'description',
       'favoriteCount',
       ...
       'taxHistory/0/taxPaid', 'taxHistory/0/time', 'taxHistory/0/value',
       'taxHistory/0/valueIncreaseRate', 'url', 'yearBuilt', 'zestimate',
       'zestimateHighPercent', 'zestimateLowPercent', 'zpid'],
      dtype='object', length=348)

In [6]:
df.tail()

,abbreviatedAddress,address/city,address/zipcode,bathrooms,bedrooms,brokerageName,dateSold,daysOnZillow,description,favoriteCount,...,taxHistory/0/taxPaid,taxHistory/0/time,taxHistory/0/value,taxHistory/0/valueIncreaseRate,url,yearBuilt,zestimate,zestimateHighPercent,zestimateLowPercent,zpid
25726,7600 SW Erica Pl,Beaverton,97008,2.0,3.0,Keller Williams Realty Portland Elite,1.595290e+12,363.0,Perfectly nestled back from the Cul-de-sac roa...,NaN,...,4647.94,1.563570e+12,225360.0,0.0,https://www.zillow.com/homedetails/7600-SW-Eri...,1977.0,489400.0,6.0,5.0,48549635
25727,7275 SW Palmer Way,Beaverton,97007,3.0,4.0,Keller Williams Realty Professionals,1.595200e+12,364.0,Contemporary Dream Home Backing To Lowami Hart...,1.0,...,6470.76,1.563570e+12,313740.0,0.0,https://www.zillow.com/homedetails/7275-SW-Pal...,1974.0,725500.0,6.0,5.0,48547614
25728,(Undisclosed Address),Beaverton,97008,2.0,2.0,Opendoor Brokerage LLC,1.622760e+12,45.0,This Beaverton two-story cul-de-sac home offer...,NaN,...,4245.13,1.563570e+12,205830.0,0.0,https://www.zillow.com/homedetails/7811-SW-Hew...,2001.0,387200.0,5.0,5.0,48581875
25729,7250 SW 70th Ave,Portland,97223,2.0,3.0,NaN,1.599000e+12,320.0,Close-in yet feels like the country. Large lot...,NaN,...,3384.07,1.563570e+12,164080.0,0.0,https://www.zillow.com/homedetails/7250-SW-70t...,1920.0,563700.0,8.0,8.0,48585019
25730,6655 SW 67th Ave,Portland,97223,3.0,4.0,"iPropertiesNW.com, LLC",1.598310e+12,328.0,Gorgeous lot backs to Hideaway Park and is ove...,NaN,...,6179.95,1.563570e+12,299640.0,0.0,https://www.zillow.com/homedetails/6655-SW-67t...,1959.0,682500.0,6.0,5.0,48584625

In [7]:
df.shape

(25731, 348)

In [8]:
df.describe()

,address/zipcode,bathrooms,bedrooms,dateSold,daysOnZillow,favoriteCount,lastSoldPrice,latitude,livingArea,longitude,...,taxHistory/0/taxIncreaseRate,taxHistory/0/taxPaid,taxHistory/0/time,taxHistory/0/value,taxHistory/0/valueIncreaseRate,yearBuilt,zestimate,zestimateHighPercent,zestimateLowPercent,zpid
count,25731.000000,25247.000000,24961.000000,2.573100e+04,25725.000000,9823.000000,2.573100e+04,25718.000000,25266.000000,25718.000000,...,24349.000000,2.430500e+04,2.434900e+04,2.432100e+04,24349.000000,25185.000000,2.375700e+04,23756.000000,23756.000000,2.573100e+04
mean,97143.830943,2.561896,3.356356,1.610792e+12,184.738620,1.436628,5.849993e+05,45.478251,2179.079237,-122.686321,...,0.097695,5.800277e+03,1.584696e+12,2.874945e+05,0.066468,1975.062140,6.441574e+05,5.836715,5.570929,1.859176e+08
std,567.759775,1.009135,1.001626,9.972007e+09,113.431466,11.370629,4.509202e+05,0.065477,1129.151916,0.144860,...,1.049283,1.026436e+04,1.596671e+10,4.602294e+05,0.828929,54.205158,3.500689e+05,1.739092,1.392246,4.555283e+08
min,7123.000000,0.000000,0.000000,1.591920e+12,1.000000,0.000000,3.000000e+02,45.258659,0.000000,-123.074242,...,-0.890731,1.970000e+00,1.465680e+12,0.000000e+00,-0.892028,0.000000,9.170000e+04,5.000000,5.000000,4.820912e+07
25%,97062.000000,2.000000,3.000000,1.601600e+12,77.000000,0.000000,3.900000e+05,45.433972,1460.000000,-122.806112,...,0.026827,3.436020e+03,1.563740e+12,1.700700e+05,0.000000,1954.000000,4.495000e+05,5.000000,5.000000,4.858769e+07
50%,97203.000000,3.000000,3.000000,1.610670e+12,185.000000,0.000000,5.220000e+05,45.488914,1996.000000,-122.674080,...,0.038119,4.646020e+03,1.595460e+12,2.339700e+05,0.029972,1981.000000,5.737000e+05,6.000000,5.000000,5.391049e+07
75%,97221.000000,3.000000,4.000000,1.620170e+12,292.000000,0.000000,6.620000e+05,45.526379,2670.000000,-122.592539,...,0.041333,6.758490e+03,1.595800e+12,3.323070e+05,0.029996,2003.000000,7.259000e+05,6.000000,6.000000,7.124459e+07
max,97267.000000,23.000000,43.000000,1.626390e+12,422.000000,295.000000,4.100000e+07,45.713860,51290.000000,-122.280975,...,123.314960,1.457247e+06,1.627330e+12,6.353208e+07,87.252000,2021.000000,6.537500e+06,53.000000,35.000000,2.146987e+09

In [9]:
df.isnull()

,abbreviatedAddress,address/city,address/zipcode,bathrooms,bedrooms,brokerageName,dateSold,daysOnZillow,description,favoriteCount,...,taxHistory/0/taxPaid,taxHistory/0/time,taxHistory/0/value,taxHistory/0/valueIncreaseRate,url,yearBuilt,zestimate,zestimateHighPercent,zestimateLowPercent,zpid
0,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,False,False,True,True,True,False
2,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,True,True,False
4,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
25727,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25728,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
25729,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
25730,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
25726    False
25727    False
25728    False
25729    False
25730    False
Length: 25731, dtype: bool

In [11]:
df.isnull().sum()

abbreviatedAddress         0
address/city               0
address/zipcode            0
bathrooms                484
bedrooms                 770
                        ...
yearBuilt                546
zestimate               1974
zestimateHighPercent    1975
zestimateLowPercent     1975
zpid                       0
Length: 348, dtype: int64

In [12]:
df.isna().sum()

abbreviatedAddress         0
address/city               0
address/zipcode            0
bathrooms                484
bedrooms                 770
                        ...
yearBuilt                546
zestimate               1974
zestimateHighPercent    1975
zestimateLowPercent     1975
zpid                       0
Length: 348, dtype: int64

In [13]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
25726    False
25727    False
25728    False
25729    False
25730    False
Length: 25731, dtype: bool

In [14]:
df.dropna()

Empty DataFrame
Columns: [abbreviatedAddress, address/city, address/zipcode, bathrooms, bedrooms, brokerageName, dateSold, daysOnZillow, description, favoriteCount, homeStatus, homeType, lastSoldPrice, latitude, livingArea, longitude, lotSize, pageViewCount, postingContact/name, price, priceHistory/0/attributeSource/infoString1, priceHistory/0/attributeSource/infoString2, priceHistory/0/attributeSource/infoString3, priceHistory/0/buyerAgent/name, priceHistory/0/buyerAgent/photo/url, priceHistory/0/buyerAgent/profileUrl, priceHistory/0/date, priceHistory/0/event, priceHistory/0/postingIsRental, priceHistory/0/price, priceHistory/0/priceChangeRate, priceHistory/0/pricePerSquareFoot, priceHistory/0/sellerAgent/name, priceHistory/0/sellerAgent/photo/url, priceHistory/0/sellerAgent/profileUrl, priceHistory/0/showCountyLink, priceHistory/0/source, priceHistory/0/time, priceHistory/1/attributeSource/infoString1, priceHistory/1/attributeSource/infoString2, priceHistory/1/attributeSource/infoString3, priceHistory/1/date, priceHistory/1/event, priceHistory/1/postingIsRental, priceHistory/1/price, priceHistory/1/priceChangeRate, priceHistory/1/pricePerSquareFoot, priceHistory/1/showCountyLink, priceHistory/1/source, priceHistory/1/time, priceHistory/2/attributeSource/infoString1, priceHistory/2/attributeSource/infoString2, priceHistory/2/attributeSource/infoString3, priceHistory/2/date, priceHistory/2/event, priceHistory/2/postingIsRental, priceHistory/2/price, priceHistory/2/priceChangeRate, priceHistory/2/pricePerSquareFoot, priceHistory/2/showCountyLink, priceHistory/2/source, priceHistory/2/time, priceHistory/3/attributeSource/infoString2, priceHistory/3/date, priceHistory/3/event, priceHistory/3/postingIsRental, priceHistory/3/price, priceHistory/3/priceChangeRate, priceHistory/3/pricePerSquareFoot, priceHistory/3/showCountyLink, priceHistory/3/source, priceHistory/3/time, priceHistory/4/attributeSource/infoString2, priceHistory/4/date, priceHistory/4/event, priceHistory/4/postingIsRental, priceHistory/4/price, priceHistory/4/priceChangeRate, priceHistory/4/pricePerSquareFoot, priceHistory/4/showCountyLink, priceHistory/4/source, priceHistory/4/time, priceHistory/5/attributeSource/infoString2, priceHistory/5/date, priceHistory/5/event, priceHistory/5/postingIsRental, priceHistory/5/price, priceHistory/5/priceChangeRate, priceHistory/5/pricePerSquareFoot, priceHistory/5/showCountyLink, priceHistory/5/source, priceHistory/5/time, priceHistory/6/attributeSource/infoString2, priceHistory/6/date, priceHistory/6/event, priceHistory/6/postingIsRental, priceHistory/6/price, priceHistory/6/priceChangeRate, priceHistory/6/pricePerSquareFoot, priceHistory/6/showCountyLink, ...]
Index: []

[0 rows x 348 columns]

In [15]:
df.dropna(axis=1)

,abbreviatedAddress,address/city,address/zipcode,dateSold,homeStatus,homeType,lastSoldPrice,price,priceHistory/0/date,priceHistory/0/event,...,resoFacts/hasAttachedProperty,resoFacts/hasGarage,resoFacts/hasHomeWarranty,resoFacts/hasLandLease,resoFacts/hasPetsAllowed,resoFacts/hasSpa,resoFacts/hasView,resoFacts/homeType,resoFacts/parking,zpid
0,2860 NE Blossom Hill Rd,Fairview,97024,1.621560e+12,RECENTLY_SOLD,TOWNHOUSE,315400,315400,5/21/2021,Sold,...,False,False,False,False,False,False,False,Townhouse,0,72258538
1,20386 NE Mackenzie Ln,Fairview,97024,1.619140e+12,RECENTLY_SOLD,SINGLE_FAMILY,400000,400000,4/23/2021,Sold,...,False,False,False,False,False,False,True,SingleFamily,1,2073593774
2,1121 SW 10th Dr,Gresham,97080,1.622760e+12,RECENTLY_SOLD,SINGLE_FAMILY,512000,512000,6/4/2021,Sold,...,False,False,False,False,False,True,True,SingleFamily,2,53959026
3,19309 NE Glisan St,Portland,97230,1.622760e+12,RECENTLY_SOLD,SINGLE_FAMILY,348000,348000,6/4/2021,Sold,...,False,False,False,False,False,False,False,SingleFamily,2,176563865
4,25-65 NW 20th St,Gresham,97030,1.622510e+12,RECENTLY_SOLD,APARTMENT,510000,510000,6/1/2021,Sold,...,False,False,False,False,False,False,False,Apartment,0,53819568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,7600 SW Erica Pl,Beaverton,97008,1.595290e+12,RECENTLY_SOLD,SINGLE_FAMILY,415000,415000,7/21/2020,Sold,...,False,False,False,False,False,False,False,SingleFamily,2,48549635
25727,7275 SW Palmer Way,Beaverton,97007,1.595200e+12,RECENTLY_SOLD,SINGLE_FAMILY,615000,615000,7/20/2020,Sold,...,False,False,False,False,False,False,True,SingleFamily,2,48547614
25728,(Undisclosed Address),Beaverton,97008,1.622760e+12,RECENTLY_SOLD,TOWNHOUSE,380000,380000,6/4/2021,Sold,...,True,True,False,False,False,False,False,Townhouse,1,48581875
25729,7250 SW 70th Ave,Portland,97223,1.599000e+12,RECENTLY_SOLD,SINGLE_FAMILY,57997,57997,9/2/2020,Sold,...,False,False,False,False,False,False,False,SingleFamily,4,48585019
25730,6655 SW 67th Ave,Portland,97223,1.598310e+12,RECENTLY_SOLD,SINGLE_FAMILY,585000,585000,8/25/2020,Sold,...,False,False,False,False,False,False,True,SingleFamily,2,48584625

In [16]:
df.dtypes

abbreviatedAddress       object
address/city             object
address/zipcode           int64
bathrooms               float64
bedrooms                float64
                         ...
yearBuilt               float64
zestimate               float64
zestimateHighPercent    float64
zestimateLowPercent     float64
zpid                      int64
Length: 348, dtype: object

In [17]:
required_columns = [
    'price',
    'bedrooms',
    'bathrooms',
    'livingArea',
    'lotSize',
    'homeType',
    'homeStatus',
    'address/city',
    'address/zipcode',
    'latitude',
    'longitude',
    'dateSold',
    'lastSoldPrice',
    'yearBuilt',
    'daysOnZillow',
    'propertyTaxRate'
]

In [18]:
df_clean = df[required_columns]
print(df_clean.columns)
df_clean.to_csv("portland_16_columns.csv", index=False)

Index(['price', 'bedrooms', 'bathrooms', 'livingArea', 'lotSize', 'homeType',
       'homeStatus', 'address/city', 'address/zipcode', 'latitude',
       'longitude', 'dateSold', 'lastSoldPrice', 'yearBuilt', 'daysOnZillow',
       'propertyTaxRate'],
      dtype='object')

In [19]:
df_clean

,price,bedrooms,bathrooms,livingArea,lotSize,homeType,homeStatus,address/city,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,yearBuilt,daysOnZillow,propertyTaxRate
0,315400,3.0,3.0,1806.0,1555.0,TOWNHOUSE,RECENTLY_SOLD,Fairview,97024,45.543571,-122.441765,1.621560e+12,315400,2007.0,25.0,1.12
1,400000,3.0,3.0,1518.0,3484.0,SINGLE_FAMILY,RECENTLY_SOLD,Fairview,97024,45.547585,-122.453224,1.619140e+12,400000,2001.0,53.0,1.12
2,512000,4.0,3.0,2724.0,9583.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97080,45.488228,-122.444420,1.622760e+12,512000,1982.0,11.0,1.12
3,348000,3.0,1.0,1217.0,13939.0,SINGLE_FAMILY,RECENTLY_SOLD,Portland,97230,45.526634,-122.464088,1.622760e+12,348000,1953.0,11.0,1.12
4,510000,6.0,3.0,2400.0,8545.0,APARTMENT,RECENTLY_SOLD,Gresham,97030,45.511238,-122.431534,1.622510e+12,510000,1967.0,14.0,1.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,415000,3.0,2.0,1378.0,10018.0,SINGLE_FAMILY,RECENTLY_SOLD,Beaverton,97008,45.465111,-122.808701,1.595290e+12,415000,1977.0,363.0,1.13
25727,615000,4.0,3.0,2176.0,9583.0,SINGLE_FAMILY,RECENTLY_SOLD,Beaverton,97007,45.467197,-122.829628,1.595200e+12,615000,1974.0,364.0,1.13
25728,380000,2.0,2.0,1466.0,1742.0,TOWNHOUSE,RECENTLY_SOLD,Beaverton,97008,NaN,NaN,1.622760e+12,380000,2001.0,45.0,1.13
25729,57997,3.0,2.0,1450.0,17859.0,SINGLE_FAMILY,RECENTLY_SOLD,Portland,97223,45.467545,-122.748367,1.599000e+12,57997,1920.0,320.0,1.13
25730,585000,4.0,3.0,2615.0,15681.0,SINGLE_FAMILY,RECENTLY_SOLD,Portland,97223,45.471767,-122.746880,1.598310e+12,585000,1959.0,328.0,1.13

In [20]:
df_clean.head()

,price,bedrooms,bathrooms,livingArea,lotSize,homeType,homeStatus,address/city,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,yearBuilt,daysOnZillow,propertyTaxRate
0,315400,3.0,3.0,1806.0,1555.0,TOWNHOUSE,RECENTLY_SOLD,Fairview,97024,45.543571,-122.441765,1.621560e+12,315400,2007.0,25.0,1.12
1,400000,3.0,3.0,1518.0,3484.0,SINGLE_FAMILY,RECENTLY_SOLD,Fairview,97024,45.547585,-122.453224,1.619140e+12,400000,2001.0,53.0,1.12
2,512000,4.0,3.0,2724.0,9583.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97080,45.488228,-122.444420,1.622760e+12,512000,1982.0,11.0,1.12
3,348000,3.0,1.0,1217.0,13939.0,SINGLE_FAMILY,RECENTLY_SOLD,Portland,97230,45.526634,-122.464088,1.622760e+12,348000,1953.0,11.0,1.12
4,510000,6.0,3.0,2400.0,8545.0,APARTMENT,RECENTLY_SOLD,Gresham,97030,45.511238,-122.431534,1.622510e+12,510000,1967.0,14.0,1.12

In [21]:
df_clean.dtypes

price                int64
bedrooms           float64
bathrooms          float64
livingArea         float64
lotSize            float64
homeType            object
homeStatus          object
address/city        object
address/zipcode      int64
latitude           float64
longitude          float64
dateSold           float64
lastSoldPrice        int64
yearBuilt          float64
daysOnZillow       float64
propertyTaxRate    float64
dtype: object

In [22]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25731 entries, 0 to 25730
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price            25731 non-null  int64
 1   bedrooms         24961 non-null  float64
 2   bathrooms        25247 non-null  float64
 3   livingArea       25266 non-null  float64
 4   lotSize          22841 non-null  float64
 5   homeType         25731 non-null  object
 6   homeStatus       25731 non-null  object
 7   address/city     25731 non-null  object
 8   address/zipcode  25731 non-null  int64
 9   latitude         25718 non-null  float64
 10  longitude        25718 non-null  float64
 11  dateSold         25731 non-null  float64
 12  lastSoldPrice    25731 non-null  int64
 13  yearBuilt        25185 non-null  float64
 14  daysOnZillow     25725 non-null  float64
 15  propertyTaxRate  25720 non-null  float64
dtypes: float64(10), int64(3), object(3)
memory usage: 3.1+ MB

In [23]:
df_clean.shape

(25731, 16)

In [24]:
df_clean.columns

Index(['price', 'bedrooms', 'bathrooms', 'livingArea', 'lotSize', 'homeType',
       'homeStatus', 'address/city', 'address/zipcode', 'latitude',
       'longitude', 'dateSold', 'lastSoldPrice', 'yearBuilt', 'daysOnZillow',
       'propertyTaxRate'],
      dtype='object')

In [25]:
df_clean.isnull()

,price,bedrooms,bathrooms,livingArea,lotSize,homeType,homeStatus,address/city,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,yearBuilt,daysOnZillow,propertyTaxRate
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25727,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25728,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
25729,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25730,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [26]:
df_clean.isnull().sum()

price                 0
bedrooms            770
bathrooms           484
livingArea          465
lotSize            2890
homeType              0
homeStatus            0
address/city          0
address/zipcode       0
latitude             13
longitude            13
dateSold              0
lastSoldPrice         0
yearBuilt           546
daysOnZillow          6
propertyTaxRate      11
dtype: int64

In [27]:
df_clean["homeType"].unique()

array(['TOWNHOUSE', 'SINGLE_FAMILY', 'APARTMENT', 'CONDO',
       'HOME_TYPE_UNKNOWN'], dtype=object)

In [28]:
df_clean["homeStatus"].unique()

array(['RECENTLY_SOLD', 'FOR_SALE', 'FOR_RENT', 'FORECLOSED',
       'PRE_FORECLOSURE'], dtype=object)

In [29]:
df_clean.loc[:,"bedrooms"]=df_clean["bedrooms"].fillna(df_clean["bedrooms"].mean())

In [30]:
df_clean.loc[:,"bathrooms"]=df_clean["bathrooms"].fillna(df_clean["bathrooms"].mean())

In [31]:
df_clean.loc[:,'latitude'] = df_clean['latitude'].fillna(df_clean['latitude'].median())

In [32]:
df_clean.loc[:,"longitude"] = df_clean["longitude"].fillna(df_clean["longitude"].median())

In [33]:
df_clean.loc[:,"livingArea"] = df_clean["livingArea"].fillna(df_clean["livingArea"].median())

In [34]:
df_clean.loc[:,"lotSize"] = df_clean["lotSize"].fillna(df_clean["lotSize"].median())

In [35]:
df_clean.loc[:,"yearBuilt"] = df_clean["yearBuilt"].fillna(df_clean["yearBuilt"].mean())

In [36]:
df_clean.loc[:,"daysOnZillow"] = df_clean["daysOnZillow"].fillna(df_clean["daysOnZillow"].median())

In [37]:
df_clean.loc[:,"propertyTaxRate"] = df_clean["propertyTaxRate"].fillna(df_clean["propertyTaxRate"].median())

In [38]:
df_clean.head(10)

,price,bedrooms,bathrooms,livingArea,lotSize,homeType,homeStatus,address/city,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,yearBuilt,daysOnZillow,propertyTaxRate
0,315400,3.0,3.0,1806.0,1555.0,TOWNHOUSE,RECENTLY_SOLD,Fairview,97024,45.543571,-122.441765,1.621560e+12,315400,2007.0,25.0,1.12
1,400000,3.0,3.0,1518.0,3484.0,SINGLE_FAMILY,RECENTLY_SOLD,Fairview,97024,45.547585,-122.453224,1.619140e+12,400000,2001.0,53.0,1.12
2,512000,4.0,3.0,2724.0,9583.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97080,45.488228,-122.444420,1.622760e+12,512000,1982.0,11.0,1.12
3,348000,3.0,1.0,1217.0,13939.0,SINGLE_FAMILY,RECENTLY_SOLD,Portland,97230,45.526634,-122.464088,1.622760e+12,348000,1953.0,11.0,1.12
4,510000,6.0,3.0,2400.0,8545.0,APARTMENT,RECENTLY_SOLD,Gresham,97030,45.511238,-122.431534,1.622510e+12,510000,1967.0,14.0,1.12
5,404200,3.0,2.0,1150.0,7000.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97080,45.487991,-122.416184,1.622510e+12,404200,1967.0,14.0,1.12
6,478200,3.0,2.0,2036.0,6969.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97030,45.498184,-122.451332,1.621560e+12,478200,1978.0,25.0,1.12
7,530000,4.0,2.0,1947.0,4791.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97080,45.467598,-122.458389,1.621470e+12,530000,2018.0,26.0,1.12
8,419900,3.0,3.0,1548.0,5009.0,SINGLE_FAMILY,FOR_SALE,Gresham,97080,45.485195,-122.418839,1.620780e+12,389200,2006.0,12.0,1.12
9,550000,3.0,3.0,2209.0,5227.0,SINGLE_FAMILY,RECENTLY_SOLD,Gresham,97080,45.475353,-122.468307,1.620170e+12,550000,2017.0,41.0,1.12

In [39]:
df_clean.head(10).isnull()

,price,bedrooms,bathrooms,livingArea,lotSize,homeType,homeStatus,address/city,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,yearBuilt,daysOnZillow,propertyTaxRate
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [40]:
df_clean=pd.get_dummies(df_clean,columns=["homeType"],dtype=int)

In [41]:
df_clean=pd.get_dummies(df_clean,columns=["address/city"],dtype=int)

In [42]:
df_clean=pd.get_dummies(df_clean,columns=["homeStatus"],dtype=int)

In [43]:
df_clean

,price,bedrooms,bathrooms,livingArea,lotSize,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,...,address/city_West Linn,address/city_Wilsonville,address/city_Wood Village,address/city_Wood village,address/city_portland,homeStatus_FORECLOSED,homeStatus_FOR_RENT,homeStatus_FOR_SALE,homeStatus_PRE_FORECLOSURE,homeStatus_RECENTLY_SOLD
0,315400,3.0,3.0,1806.0,1555.0,97024,45.543571,-122.441765,1.621560e+12,315400,...,0,0,0,0,0,0,0,0,0,1
1,400000,3.0,3.0,1518.0,3484.0,97024,45.547585,-122.453224,1.619140e+12,400000,...,0,0,0,0,0,0,0,0,0,1
2,512000,4.0,3.0,2724.0,9583.0,97080,45.488228,-122.444420,1.622760e+12,512000,...,0,0,0,0,0,0,0,0,0,1
3,348000,3.0,1.0,1217.0,13939.0,97230,45.526634,-122.464088,1.622760e+12,348000,...,0,0,0,0,0,0,0,0,0,1
4,510000,6.0,3.0,2400.0,8545.0,97030,45.511238,-122.431534,1.622510e+12,510000,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,415000,3.0,2.0,1378.0,10018.0,97008,45.465111,-122.808701,1.595290e+12,415000,...,0,0,0,0,0,0,0,0,0,1
25727,615000,4.0,3.0,2176.0,9583.0,97007,45.467197,-122.829628,1.595200e+12,615000,...,0,0,0,0,0,0,0,0,0,1
25728,380000,2.0,2.0,1466.0,1742.0,97008,45.488914,-122.674080,1.622760e+12,380000,...,0,0,0,0,0,0,0,0,0,1
25729,57997,3.0,2.0,1450.0,17859.0,97223,45.467545,-122.748367,1.599000e+12,57997,...,0,0,0,0,0,0,0,0,0,1
25730,585000,4.0,3.0,2615.0,15681.0,97223,45.471767,-122.746880,1.598310e+12,585000,...,0,0,0,0,0,0,0,0,0,1

In [44]:
df_clean.dtypes

price                           int64
bedrooms                      float64
bathrooms                     float64
livingArea                    float64
lotSize                       float64
address/zipcode                 int64
latitude                      float64
longitude                     float64
dateSold                      float64
lastSoldPrice                   int64
yearBuilt                     float64
daysOnZillow                  float64
propertyTaxRate               float64
homeType_APARTMENT              int64
homeType_CONDO                  int64
homeType_HOME_TYPE_UNKNOWN      int64
homeType_SINGLE_FAMILY          int64
homeType_TOWNHOUSE              int64
address/city_Aloha              int64
address/city_Beavercreek        int64
address/city_Beaverton          int64
address/city_Boring             int64
address/city_Clackamas          int64
address/city_Corbett            int64
address/city_Cornelius          int64
address/city_Damascus           int64
address/city_Estacada           int64
address/city_Fairview           int64
address/city_Gladstone          int64
address/city_Gresham            int64
address/city_HAPPY VALLEY       int64
address/city_Happy Valley       int64
address/city_Hillsboro          int64
address/city_King City          int64
address/city_King city          int64
address/city_Lake Oswego        int64
address/city_Lake oswego        int64
address/city_Millwaukie         int64
address/city_Milwaukie          int64
address/city_Molalla            int64
address/city_Newberg            int64
address/city_Oregon City        int64
address/city_PORTLAND           int64
address/city_Portland           int64
address/city_Scappoose          int64
address/city_Sherwood           int64
address/city_Tigard             int64
address/city_Troutdale          int64
address/city_Tualatin           int64
address/city_West Linn          int64
address/city_Wilsonville        int64
address/city_Wood Village       int64
address/city_Wood village       int64
address/city_portland           int64
homeStatus_FORECLOSED           int64
homeStatus_FOR_RENT             int64
homeStatus_FOR_SALE             int64
homeStatus_PRE_FORECLOSURE      int64
homeStatus_RECENTLY_SOLD        int64
dtype: object

In [45]:
num_cols=[
    'price',
    'bedrooms',
    'bathrooms',
    'livingArea',
    'lotSize',
    'address/zipcode',
    'latitude',
    'longitude',
    'dateSold',
    'lastSoldPrice',
    'yearBuilt',
    'daysOnZillow',
    'propertyTaxRate'
]

In [46]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df_clean[num_cols]=scaler.fit_transform(df_clean[num_cols])

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
df_clean[num_cols].head()

,price,bedrooms,bathrooms,livingArea,lotSize,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,yearBuilt,daysOnZillow,propertyTaxRate
0,315400,3.0,3.0,1806.0,1555.0,97024,45.543571,-122.441765,1.621560e+12,315400,2007.0,25.0,1.12
1,400000,3.0,3.0,1518.0,3484.0,97024,45.547585,-122.453224,1.619140e+12,400000,2001.0,53.0,1.12
2,512000,4.0,3.0,2724.0,9583.0,97080,45.488228,-122.444420,1.622760e+12,512000,1982.0,11.0,1.12
3,348000,3.0,1.0,1217.0,13939.0,97230,45.526634,-122.464088,1.622760e+12,348000,1953.0,11.0,1.12
4,510000,6.0,3.0,2400.0,8545.0,97030,45.511238,-122.431534,1.622510e+12,510000,1967.0,14.0,1.12

In [ ]:
price_bins=[0,0.33,0.66,1.0]
price_labels=["Low","Median","High"]
df_clean["price_bin"]=pd.cut(df_clean["price"],bins=price_bins,labels=price_labels)

In [ ]:
area_bins=[0,0.33,0.66,1.0]
area_labels=["small","Median","large"]
df_clean["livingArea_bin"]=pd.cut(df_clean["livingArea"],bins=area_bins,labels=area_labels)

In [ ]:
df_clean

,price,bedrooms,bathrooms,livingArea,lotSize,address/zipcode,latitude,longitude,dateSold,lastSoldPrice,...,address/city_Wood Village,address/city_Wood village,address/city_portland,homeStatus_FORECLOSED,homeStatus_FOR_RENT,homeStatus_FOR_SALE,homeStatus_PRE_FORECLOSURE,homeStatus_RECENTLY_SOLD,price_bin,livingArea_bin
0,0.007685,0.069767,0.130435,0.035212,0.000007,0.997304,0.625905,0.797307,0.859878,0.007685,...,0,0,0,0,0,0,0,1,Low,small
1,0.009749,0.069767,0.130435,0.029596,0.000017,0.997304,0.634721,0.782861,0.789672,0.009749,...,0,0,0,0,0,0,0,1,Low,small
2,0.012481,0.093023,0.130435,0.053110,0.000046,0.997926,0.504324,0.793960,0.894691,0.012481,...,0,0,0,0,0,0,0,1,Low,small
3,0.008481,0.069767,0.043478,0.023728,0.000067,0.999590,0.588697,0.769166,0.894691,0.008481,...,0,0,0,0,0,0,0,1,Low,small
4,0.012432,0.139535,0.130435,0.046793,0.000041,0.997371,0.554874,0.810204,0.887438,0.012432,...,0,0,0,0,0,0,0,1,Low,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,0.010115,0.069767,0.086957,0.026867,0.000048,0.997127,0.453540,0.334744,0.097766,0.010115,...,0,0,0,0,0,0,0,1,Low,small
25727,0.014993,0.093023,0.130435,0.042425,0.000046,0.997116,0.458124,0.308363,0.095155,0.014993,...,0,0,0,0,0,0,0,1,Low,small
25728,0.009261,0.046512,0.086957,0.028583,0.000008,0.997127,0.505833,0.504448,0.894691,0.009261,...,0,0,0,0,0,0,0,1,Low,small
25729,0.001407,0.069767,0.086957,0.028271,0.000086,0.999512,0.458886,0.410801,0.205396,0.001407,...,0,0,0,0,0,0,0,1,Low,small
25730,0.014261,0.093023,0.130435,0.050985,0.000075,0.999512,0.468163,0.412676,0.185379,0.014261,...,0,0,0,0,0,0,0,1,Low,small

In [ ]:
df_clean.to_csv("portland_preprocessing_dataset.csv",index=False)

In [47]:
import os
os.getcwd()

'/home/user/Downloads'